using System;

namespace Xwt.GoogleMaterialDesignIcons
{
	public class AvIconId
	{
		public const string AddToQueue = "AddToQueue";
		public const string Airplay = "Airplay";
		public const string Album = "Album";
		public const string ArtTrack = "ArtTrack";
		public const string AvTimer = "AvTimer";
		public const string BrandingWatermark = "BrandingWatermark";
		public const string CallToAction = "CallToAction";
		public const string ClosedCaption = "ClosedCaption";
		public const string Equalizer = "Equalizer";
		public const string Explicit = "Explicit";
		public const string FastForward = "FastForward";
		public const string FastRewind = "FastRewind";
		public const string FeaturedPlayList = "FeaturedPlayList";
		public const string FeaturedVideo = "FeaturedVideo";
		public const string FiberDvr = "FiberDvr";
		public const string FiberManualRecord = "FiberManualRecord";
		public const string FiberNew = "FiberNew";
		public const string FiberPin = "FiberPin";
		public const string FiberSmartRecord = "FiberSmartRecord";
		public const string Forward10 = "Forward10";
		public const string Forward30 = "Forward30";
		public const string Forward5 = "Forward5";
		public const string Games = "Games";
		public const string Hearing = "Hearing";
		public const string HighQuality = "HighQuality";
		public const string LibraryAdd = "LibraryAdd";
		public const string LibraryBooks = "LibraryBooks";
		public const string LibraryMusic = "LibraryMusic";
		public const string Loop = "Loop";
		public const string Mic = "Mic";
		public const string MicNone = "MicNone";
		public const string MicOff = "MicOff";
		public const string Movie = "Movie";
		public const string MusicVideo = "MusicVideo";
		public const string NewReleases = "NewReleases";
		public const string Note = "Note";
		public const string NotInterested = "NotInterested";
		public const string Pause = "Pause";
		public const string PauseCircleFilled = "PauseCircleFilled";
		public const string PauseCircleOutline = "PauseCircleOutline";
		public const string PlayArrow = "PlayArrow";
		public const string PlayCircleFilled = "PlayCircleFilled";
		public const string PlayCircleFilledWhite = "PlayCircleFilledWhite";
		public const string PlayCircleOutline = "PlayCircleOutline";
		public const string PlaylistAdd = "PlaylistAdd";
		public const string PlaylistAddCheck = "PlaylistAddCheck";
		public const string PlaylistPlay = "PlaylistPlay";
		public const string Queue = "Queue";
		public const string QueueMusic = "QueueMusic";
		public const string QueuePlayNext = "QueuePlayNext";
		public const string Radio = "Radio";
		public const string RecentActors = "RecentActors";
		public const string RemoveFromQueue = "RemoveFromQueue";
		public const string Repeat = "Repeat";
		public const string RepeatOne = "RepeatOne";
		public const string Replay10 = "Replay10";
		public const string Replay30 = "Replay30";
		public const string Replay = "Replay";
		public const string Replay5 = "Replay5";
		public const string Shuffle = "Shuffle";
		public const string SkipNext = "SkipNext";
		public const string SkipPrevious = "SkipPrevious";
		public const string SlowMotionVideo = "SlowMotionVideo";
		public const string Snooze = "Snooze";
		public const string Stop = "Stop";
		public const string Subscriptions = "Subscriptions";
		public const string Subtitles = "Subtitles";
		public const string SurroundSound = "SurroundSound";
		public const string VideoCall = "VideoCall";
		public const string Videocam = "Videocam";
		public const string VideocamOff = "VideocamOff";
		public const string VideoLabel = "VideoLabel";
		public const string VideoLibrary = "VideoLibrary";
		public const string VolumeDown = "VolumeDown";
		public const string VolumeMute = "VolumeMute";
		public const string VolumeOff = "VolumeOff";
		public const string VolumeUp = "VolumeUp";
		public const string Web = "Web";
		public const string WebAsset = "WebAsset";
	}
}
