using System;

namespace Xwt.GoogleMaterialDesignIcons
{
	public class DeviceIconId
	{
		public const string AccessAlarm = "AccessAlarm";
		public const string AccessAlarms = "AccessAlarms";
		public const string AccessTime = "AccessTime";
		public const string AddAlarm = "AddAlarm";
		public const string AirplanemodeActive = "AirplanemodeActive";
		public const string AirplanemodeInactive = "AirplanemodeInactive";
		public const string Battery20 = "Battery20";
		public const string Battery30 = "Battery30";
		public const string Battery50 = "Battery50";
		public const string Battery60 = "Battery60";
		public const string Battery80 = "Battery80";
		public const string Battery90 = "Battery90";
		public const string BatteryAlert = "BatteryAlert";
		public const string BatteryCharging20 = "BatteryCharging20";
		public const string BatteryCharging30 = "BatteryCharging30";
		public const string BatteryCharging50 = "BatteryCharging50";
		public const string BatteryCharging60 = "BatteryCharging60";
		public const string BatteryCharging80 = "BatteryCharging80";
		public const string BatteryCharging90 = "BatteryCharging90";
		public const string BatteryChargingFull = "BatteryChargingFull";
		public const string BatteryFull = "BatteryFull";
		public const string BatteryStd = "BatteryStd";
		public const string BatteryUnknown = "BatteryUnknown";
		public const string Bluetooth = "Bluetooth";
		public const string BluetoothConnected = "BluetoothConnected";
		public const string BluetoothDisabled = "BluetoothDisabled";
		public const string BluetoothSearching = "BluetoothSearching";
		public const string BrightnessAuto = "BrightnessAuto";
		public const string BrightnessHigh = "BrightnessHigh";
		public const string BrightnessLow = "BrightnessLow";
		public const string BrightnessMedium = "BrightnessMedium";
		public const string DataUsage = "DataUsage";
		public const string DeveloperMode = "DeveloperMode";
		public const string Devices = "Devices";
		public const string Dvr = "Dvr";
		public const string GpsFixed = "GpsFixed";
		public const string GpsNotFixed = "GpsNotFixed";
		public const string GpsOff = "GpsOff";
		public const string GraphicEq = "GraphicEq";
		public const string LocationDisabled = "LocationDisabled";
		public const string LocationSearching = "LocationSearching";
		public const string NetworkCell = "NetworkCell";
		public const string NetworkWifi = "NetworkWifi";
		public const string Nfc = "Nfc";
		public const string ScreenLockLandscape = "ScreenLockLandscape";
		public const string ScreenLockPortrait = "ScreenLockPortrait";
		public const string ScreenLockRotation = "ScreenLockRotation";
		public const string ScreenRotation = "ScreenRotation";
		public const string SdStorage = "SdStorage";
		public const string SettingsSystemDaydream = "SettingsSystemDaydream";
		public const string SignalCellular0Bar = "SignalCellular0Bar";
		public const string SignalCellular1Bar = "SignalCellular1Bar";
		public const string SignalCellular2Bar = "SignalCellular2Bar";
		public const string SignalCellular3Bar = "SignalCellular3Bar";
		public const string SignalCellular4Bar = "SignalCellular4Bar";
		public const string SignalCellularConnectedNoInternet0Bar = "SignalCellularConnectedNoInternet0Bar";
		public const string SignalCellularConnectedNoInternet1Bar = "SignalCellularConnectedNoInternet1Bar";
		public const string SignalCellularConnectedNoInternet2Bar = "SignalCellularConnectedNoInternet2Bar";
		public const string SignalCellularConnectedNoInternet3Bar = "SignalCellularConnectedNoInternet3Bar";
		public const string SignalCellularConnectedNoInternet4Bar = "SignalCellularConnectedNoInternet4Bar";
		public const string SignalCellularNoSim = "SignalCellularNoSim";
		public const string SignalCellularNull = "SignalCellularNull";
		public const string SignalCellularOff = "SignalCellularOff";
		public const string SignalWifi0Bar = "SignalWifi0Bar";
		public const string SignalWifi1Bar = "SignalWifi1Bar";
		public const string SignalWifi1BarLock = "SignalWifi1BarLock";
		public const string SignalWifi2Bar = "SignalWifi2Bar";
		public const string SignalWifi2BarLock = "SignalWifi2BarLock";
		public const string SignalWifi3Bar = "SignalWifi3Bar";
		public const string SignalWifi3BarLock = "SignalWifi3BarLock";
		public const string SignalWifi4Bar = "SignalWifi4Bar";
		public const string SignalWifi4BarLock = "SignalWifi4BarLock";
		public const string SignalWifiOff = "SignalWifiOff";
		public const string Storage = "Storage";
		public const string Usb = "Usb";
		public const string Wallpaper = "Wallpaper";
		public const string Widgets = "Widgets";
		public const string WifiLock = "WifiLock";
		public const string WifiTethering = "WifiTethering";
	}
}
